# Generated by Django 4.2.1 on 2023-06-01 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_product_available_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deliver_charge', models.IntegerField()),
                ('delivery_address', models.TextField()),
                ('alter_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('upi', 'upi')], max_length=255)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('no_of_items', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
