# Generated by Django 4.2.1 on 2023-05-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodictorder',
            name='alter_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prodictorder',
            name='no_of_items',
            field=models.IntegerField(default=1),
        ),
    ]
