# Generated by Django 4.2.1 on 2023-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_sell',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
