# Generated by Django 4.2.1 on 2023-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('tshirt', 'tshirt')], max_length=255, null=True),
        ),
    ]
