# Generated by Django 4.2.1 on 2023-05-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('tshirt', 'tshirt'), ('shirt', 'shirt'), ('mobile', 'mobile')], max_length=255, null=True),
        ),
    ]
