# Generated by Django 4.2.1 on 2023-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
