version: "3.3"
services:
  django-with-db:
    build: .
    volumes:
      - .:/Ecommerce-app
    ports:
      - "8005:8005"
    image: ecommerce:django
    container_name: ecommerce_django_app_container
    command: python manage.py runserver 0.0.0.0:8005
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mohan.pandit@visiontrek.in
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80 #default port
    ports:
      - "5050:80"
    volumes:
      - ./data/db:/var/lib/pgadmin4
  react-app:
    build: ../react_app/
    container_name: react-container
    image: ecommerce:react
    volumes:
      - .:/Ecommerce-app
    ports:
      - "3000:3000"





